//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backers.
        /// </summary>
        internal static string Backers {
            get {
                return ResourceManager.GetString("Backers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a Pro.
        /// </summary>
        internal static string BookAPro {
            get {
                return ResourceManager.GetString("BookAPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro gamers haven&apos;t made available dates to book yet....
        /// </summary>
        internal static string BookAProText {
            get {
                return ResourceManager.GetString("BookAProText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dotabuff profile in a new tab?.
        /// </summary>
        internal static string ConfirmPlayerProfile {
            get {
                return ResourceManager.GetString("ConfirmPlayerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days left.
        /// </summary>
        internal static string DaysToGo {
            get {
                return ResourceManager.GetString("DaysToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dotabuff profile.
        /// </summary>
        internal static string DotaBuffProfile {
            get {
                return ResourceManager.GetString("DotaBuffProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dota&lt;span&gt;hunt&lt;/span&gt;.
        /// </summary>
        internal static string DotaHuntLogo {
            get {
                return ResourceManager.GetString("DotaHuntLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to funded.
        /// </summary>
        internal static string Funded {
            get {
                return ResourceManager.GetString("Funded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire a Pro.
        /// </summary>
        internal static string HireAPro {
            get {
                return ResourceManager.GetString("HireAPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire List.
        /// </summary>
        internal static string HireList {
            get {
                return ResourceManager.GetString("HireList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        internal static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pledged.
        /// </summary>
        internal static string Pledged {
            get {
                return ResourceManager.GetString("Pledged", resourceCulture);
            }
        }
    }
}
