//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgamersView
    {
        public string ProviderKey { get; set; }
        public string Id { get; set; }
        public string UserName { get; set; }
        public string ProfileUrl { get; set; }
    }
}
