//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushiDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionBid
    {
        public string BidId { get; set; }
        public System.DateTime Time { get; set; }
        public string AuctionId { get; set; }
        public string BuyerId { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PlayerAuction PlayerAuction { get; set; }
    }
}
