//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushiDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameOrder
    {
        public string OrderId { get; set; }
        public int StateId { get; set; }
        public string BuyerId { get; set; }
        public string SellerId { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public decimal OrderPrice { get; set; }
        public string MatchId { get; set; }
        public string RoomId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Progamer Progamer { get; set; }
        public virtual GameOrderState GameOrderState { get; set; }
        public virtual ReportedOrder ReportedOrder { get; set; }
        public virtual PayPal PayPal { get; set; }
    }
}
