//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushiDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HireAProEntities : DbContext
    {
        public HireAProEntities()
            : base("name=HireAProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AuctionBid> AuctionBids { get; set; }
        public virtual DbSet<AuctionState> AuctionStates { get; set; }
        public virtual DbSet<GameOrder> GameOrders { get; set; }
        public virtual DbSet<GameOrderState> GameOrderStates { get; set; }
        public virtual DbSet<PayPal> PayPals { get; set; }
        public virtual DbSet<PlayerAuction> PlayerAuctions { get; set; }
        public virtual DbSet<Progamer> Progamers { get; set; }
        public virtual DbSet<ReportedOrder> ReportedOrders { get; set; }
        public virtual DbSet<ProgamersView> ProgamersViews { get; set; }
        public virtual DbSet<SteamRequest> SteamRequests { get; set; }
        public virtual DbSet<UsersView> UsersViews { get; set; }
    }
}
