//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushiDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgamersView
    {
        public string ProviderKey { get; set; }
        public string Id { get; set; }
        public string UserName { get; set; }
        public string ProfileUrl { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> AuctionStartPrice { get; set; }
        public Nullable<decimal> AuctionLimit { get; set; }
        public Nullable<int> Status { get; set; }
        public string PayPalEmail { get; set; }
        public string AvatarUrl { get; set; }
    }
}
