//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushiDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progamer
    {
        public Progamer()
        {
            this.GameOrders = new HashSet<GameOrder>();
            this.PlayerAuctions = new HashSet<PlayerAuction>();
        }
    
        public string UserId { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> AuctionStartPrice { get; set; }
        public Nullable<decimal> AuctionLimit { get; set; }
        public Nullable<int> Status { get; set; }
        public string PayPalEmail { get; set; }
        public string ProfileUrl { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<GameOrder> GameOrders { get; set; }
        public virtual ICollection<PlayerAuction> PlayerAuctions { get; set; }
    }
}
