//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushiDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportedOrder
    {
        public string OrderId { get; set; }
        public Nullable<System.DateTime> ReportedTime { get; set; }
        public string ReportedMessage { get; set; }
    
        public virtual GameOrder GameOrder { get; set; }
    }
}
