//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushiDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SteamRequest
    {
        public System.DateTime Day { get; set; }
        public Nullable<int> SignUp { get; set; }
        public Nullable<int> SignIn { get; set; }
        public Nullable<int> HireAPro { get; set; }
        public Nullable<int> GameCheck { get; set; }
        public Nullable<int> PreGame { get; set; }
        public Nullable<int> ProLoad { get; set; }
    }
}
